#!/bin/bash

set -eu
#
vagrant_cmd=$(which vagrant)
vagrant_hostname=docker_norikra

#
ssh_cmd=$(which ssh)
ssh_config_to_vagrant=$(pwd)/.ssh_config
${vagrant_cmd} ssh-config --host ${vagrant_hostname} > ${ssh_config_to_vagrant}
ssh_opts="-F ${ssh_config_to_vagrant} -q"
ssh_cmd="${ssh_cmd} ${ssh_opts}"

#
docker_cmd=$(ssh -F ${ssh_config_to_vagrant} ${vagrant_hostname} 'which docker')
docker_opts="-H :5432"
docker_cmd="${docker_cmd} ${docker_opts}"
docker_share_dir=/opt/docker # on docker host
docker_repository_name=sgykfjsm
base_container_name=base_ubuntu
data_container_name=data
app_container_name=norikra
docker_data_dir=${docker_share_dir}/${data_container_name}

#
rake_cmd=$(which rake)

echo "Initialize:"
for cid in $(${ssh_cmd} ${vagrant_hostname} "${docker_cmd} ps -a -q --no-trunc")
do
    echo ${cid}
    ${ssh_cmd} ${vagrant_hostname} " \
        ${docker_cmd} stop ${cid} > /dev/null \
        && ${docker_cmd} rm ${cid} > /dev/null \
    "
done

echo "Pull docker image(${base_container_name}):"
${ssh_cmd} ${vagrant_hostname} \
    "${docker_cmd} pull ${docker_repository_name}/${base_container_name}"
echo

for cn in ${app_container_name}
do
    dockerfile=
    case "${cn}" in
        "norikra" )
            dockerfile="/vagrant/docker/."
            ;;
        * )
            echo "unknown container name: ${cn}" >&2
            exit 1
            ;;
    esac

    echo "Build docker image(${cn}):"
    ${ssh_cmd} ${vagrant_hostname} \
        "${docker_cmd} build -t ${docker_repository_name}/${cn} ${dockerfile}"
    echo
done


echo "Run container:"
${ssh_cmd} ${vagrant_hostname} <<EOF
sudo rm -rf ${docker_data_dir}
sudo mkdir -m 777 -p ${docker_data_dir}/var/log/norikra

echo -n "data container: "
${docker_cmd} run -i -d -t -P \
    --name ${data_container_name} \
    -v ${docker_data_dir}/var/log:/var/log \
    -v /etc/localtime:/etc/localtime:ro \
    ${docker_repository_name}/${base_container_name}

echo -n "application container: "
${docker_cmd} run -i -d -t \
    -p 46578:26578 \
    --name ${app_container_name} \
    --volumes-from ${data_container_name} \
    -v /etc/localtime:/etc/localtime:ro \
    ${docker_repository_name}/${app_container_name}
EOF

echo Please wait for 60 sec...
sleep 60

set +e
echo "Run rspec test:"
${rake_cmd} spec
echo

# set -e
# echo "Delete container:"
#
# for cid in $(${ssh_cmd} ${vagrant_hostname} "${docker_cmd} ps -a -q --no-trunc")
# do
#     echo ${cid}
#     ${ssh_cmd} ${vagrant_hostname} " \
#         ${docker_cmd} stop ${cid} > /dev/null \
#         && ${docker_cmd} rm ${cid} > /dev/null \
#     "
# done
#
rm -f ${ssh_config_to_vagrant}
exit
