#!/bin/bash

set -eu

#
vagrant_cmd=$(which vagrant)
vagrant_hostname="play-scala-intro"

#
ssh_cmd=$(which ssh)
ssh_config_to_vagrant=$(pwd)/.ssh_config
${vagrant_cmd} ssh-config --host ${vagrant_hostname} > ${ssh_config_to_vagrant}
ssh_opts="-F ${ssh_config_to_vagrant} -q"
ssh_cmd="${ssh_cmd} ${ssh_opts}"

#
docker_cmd=$(ssh -F ${ssh_config_to_vagrant} ${vagrant_hostname} 'which docker')
docker_opts="-H :5432"
docker_cmd="${docker_cmd} ${docker_opts}"
docker_share_dir=/opt/docker # on docker host
docker_repository_name=sgykfjsm
base_container_name=base_ubuntu
app_container_name=play-scala-intro

#
rake_cmd=$(which rake)

initialize() {
    for cid in $(${ssh_cmd} ${vagrant_hostname} "${docker_cmd} ps -a -q --no-trunc")
    do
        echo "$(date '+%FT%T.%Z') Remove Container: ${cid}"
        ${ssh_cmd} ${vagrant_hostname} " \
            ${docker_cmd} stop ${cid} > /dev/null \
            && ${docker_cmd} rm -f ${cid} > /dev/null
        "
    done

    for iid in $(${ssh_cmd} ${vagrant_hostname} "${docker_cmd} images -q --no-trunc")
    do
        echo "$(date '+%FT%T.%Z') Remove Image: ${iid}"
        ${ssh_cmd} ${vagrant_hostname} " \
            ${docker_cmd} rmi --force ${iid} > /dev/null
        "
    done
}

cleanup() {
    initialize
    rm -f ${ssh_config_to_vagrant}

}

pull_image() {
    ${ssh_cmd} ${vagrant_hostname} \
        "${docker_cmd} pull ${docker_repository_name}/${base_container_name}"
}

build_image() {
    ${ssh_cmd} ${vagrant_hostname} \
        "${docker_cmd} build -t ${docker_repository_name}/${app_container_name} /vagrant/docker/."
}

run_container() {
    ${ssh_cmd} ${vagrant_hostname} <<EOF
# application container
${docker_cmd} run -i -d -t \
    -p 12812:2812 \
    -p 10080:9000 \
    --name ${app_container_name} \
    -v /etc/localtime:/etc/localtime:ro \
    ${docker_repository_name}/${app_container_name}
EOF
}

echo "$(date '+%FT%T.%Z') Initialize"
initialize

echo "$(date '+%FT%T.%Z') Pull docker base image(${base_container_name}):"
pull_image

echo "$(date '+%FT%T.%Z') Build docker image(${app_container_name}):"
build_image

echo "$(date '+%FT%T.%Z') Run container:"
run_container

# sleep 10
#
# set +e
# echo "$(date '+%FT%T.%Z') Run rspec test:"
# ${rake_cmd} spec
#
# set -e
#
# echo "$(date '+%FT%T.%Z') CleanUp"
# cleanup

exit
